

spring:
  datasource:
    url: jdbc:mysql://111.229.237.107:3310/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
    - classpath:mbgmapper/*.xml
#
#jwt:
#   tokenHeader: Authorization #JWT\u5B58\u50A8\u7684\u8BF7\u6C42\u5934
#   secret: vote #JWT\u52A0\u89E3\u5BC6\u4F7F\u7528\u7684\u5BC6\u94A5
#   expiration: 604800 #JWT\u7684\u8D85\u671F\u9650\u65F6\u95F4(60*60*24*7)
#   tokenHead: Bearer  #JWT\u8D1F\u8F7D\u4E2D\u62FF\u5230\u5F00\u5934
  # log-impl:
  #   org.apache.logging.stdout.StdOutImpl